#!/usr/bin/env python3
"""Dependency Review Script

Reads `pyproject.toml`, extracts the list of dependencies, determines the latest version
available on PyPI for each package, and generates a markdown report `dependency_review_report.md`.
The report includes:
- Current version constraint from pyproject.toml
- Latest version on PyPI
- Recommendation to upgrade (if newer version exists)
- Justification placeholder for any pinned exact versions (none in this project).
"""

import tomllib
import json
import urllib.request
from pathlib import Path

PYPROJECT_PATH = Path(__file__).resolve().parents[1] / "pyproject.toml"
REPORT_PATH = Path(__file__).resolve().parents[1] / "dependency_review_report.md"

def load_pyproject():
    with open(PYPROJECT_PATH, "rb") as f:
        data = tomllib.load(f)
    return data

def parse_dependencies(data):
    deps = data.get("project", {}).get("dependencies", [])
    # Remove comments and empty strings
    cleaned = []
    for dep in deps:
        dep = dep.strip()
        if not dep or dep.startswith("#"):
            continue
        cleaned.append(dep)
    return cleaned

def extract_package_name(dep_str: str):
    # dep_str format: "package>=x.y.z" or "package[extra]>=x.y.z"
    # Split on first "[" to remove extras, then on first comparison operator
    name_part = dep_str.split("[")[0]
    for op in ["<=", ">=", "==", "!=", "~=", "<", ">"]:
        if op in name_part:
            name = name_part.split(op)[0]
            version = name_part.split(op)[1]
            return name.strip(), op, version.strip()
    # Fallback: no operator, treat whole as name
    return name_part.strip(), "", ""

def fetch_latest_version(package: str) -> str:
    url = f"https://pypi.org/pypi/{package}/json"
    try:
        with urllib.request.urlopen(url) as resp:
            data = json.load(resp)
        return data["info"]["version"]
    except Exception as e:
        return "unknown"

def generate_report(dependencies):
    lines = ["# Dependency Review Report", "", "Generated by dependency_review.py", ""]
    lines.append("| Package | Current Constraint | Latest Version | Recommendation |")
    lines.append("|---|---|---|---|")
    for dep in dependencies:
        pkg, op, cur_version = extract_package_name(dep)
        latest = fetch_latest_version(pkg)
        if latest == "unknown":
            rec = "Unable to fetch"
        else:
            if op and cur_version:
                # Compare versions as strings; simple check
                if latest != cur_version:
                    rec = f"Upgrade to {latest}"
                else:
                    rec = "Up‑to‑date"
            else:
                rec = "No constraint"
        lines.append(f"| {pkg} | {dep} | {latest} | {rec} |")
    # Identify top ten by order of appearance (could be refined)
    top_ten = dependencies[:10]
    lines.append("\n## Top Ten Key Dependencies")
    for i, dep in enumerate(top_ten, 1):
        pkg, _, _ = extract_package_name(dep)
        lines.append(f"{i}. {pkg}")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Report written to {REPORT_PATH}")

def main():
    data = load_pyproject()
    deps = parse_dependencies(data)
    generate_report(deps)

if __name__ == "__main__":
    main()
